services:
  - type: web
    name: movie-recom-api
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: movie-recom-ui
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_BASE
        fromService:
          type: web
          name: movie-recom-api
          property: host
      - key: PYTHON_VERSION
        value: 3.10.0
